### ISSUE TITLE
Provide Tracking Algorithm with zoom state

### ISSUE THREAD

**Issue by justayak** [BioroboticsLab/biotracker_core#54]
I think it could be useful if we provide the current zoom state to the tracking algorithm as part of the paint API in the form:

``` c
struct PanZoomState {
    float zoomFactor = 0.f;
    float panX       = 0.f;
    float panY       = 0.f;
    bool isChanged = false;
};
```

rather then to let each tracker try to keep track of that by itself due to mouse click and zoom events.

**Comment by nebw** [comment]
Hey, two questions:

1) By part of the paint API, do you mean as a parameter of the paint function? 
2) Are there any tracking algorithms that try to keep track of the zoom state manually? Why would they do that?

**Comment by justayak** [comment]
regarding 1.) Yes, I would provide it as part of the paint function
regarding 2.) I dont know but I did not feel comfortable to judge that myself. E.g. if you have very complex drawing, you could try to exclusively draw in the visible field etc. but thats just a suggestion.

If you cannot think of a tracker that might need that: great, as I would just close this ticket and do not change the trackers api

**Comment by timlandgraf** [comment]
consider the BeesBook case: when zoomed out we would like to see boxes where the tags were detected and when zoomed in on a single tag, we might want to see the grid. I guess the framework should at least provide an interface the ask what the current zoom is for the module to decide what to paint

**Comment by justayak** [comment]
Ok, so I believe the extension of the draw function to be the most simple and descriptive way of communication the zoom level (+ the panning) so I will implement it that way if nobody objects

**Comment by nebw** [comment]
I object. I just had a look at the TrackingAlgorithm interface and we do already have a slot called setZoomLevel(float zLevel), which should be called from the VideoView after each change to the zoom level. One could argue that the same should be done for the current pan as well. However, I don't think that this should be an argument to the paint method because:
a) unnecessary copies with each call of the paint method
b) the tracking algorithms that use the current zoom level do so by using the member variable _currentZoomLevel, which is set by the setZoomLevel. Moving this to the paint method seem like a change without any benefits, unless I'm missing something.

**Comment by justayak** [comment]
This is true if we do not need any more information than the zoom level.
